#!/bin/sh
# SparrowOS — Provision AI coding tools into a tenant jail
#
# Installs one or more AI CLI tools (claude, codex, gemini) into a running
# tenant jail.  Ensures Node.js is available, installs each requested tool,
# and configures PF rules for outbound API access.
#
# Usage:
#   tenant-ai-provision.sh <tenant_name> <tool1[,tool2,...]>
#
# Examples:
#   tenant-ai-provision.sh dev01 claude
#   tenant-ai-provision.sh dev01 claude,codex,gemini
#
# Must be run as root.

set -eu

NODE_PKG="node20"
NPM_PKG="npm-node20"
PF_ANCHOR="sparrow-tenant-ai"
SPARROW_CONF_DIR="/usr/local/etc/sparrow/tenants"

# NPM package names for each supported AI tool
CLAUDE_PKG="@anthropic-ai/claude-code"
CODEX_PKG="@openai/codex"
GEMINI_PKG="@anthropic-ai/gemini-cli"

# API endpoint domains for PF rules
CLAUDE_HOSTS="api.anthropic.com"
CODEX_HOSTS="api.openai.com"
GEMINI_HOSTS="generativelanguage.googleapis.com"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log() {
    printf '[sparrow-ai-provision] %s\n' "$*"
}

die() {
    log "ERROR: $*" >&2
    exit 1
}

usage() {
    printf 'Usage: %s <tenant_name> <tool1[,tool2,...]>\n' "$(basename "$0")" >&2
    printf '  Supported tools: claude, codex, gemini\n' >&2
    exit 1
}

jail_exec() {
    jexec "$TENANT" "$@"
}

# ---------------------------------------------------------------------------
# Node.js installation
# ---------------------------------------------------------------------------

ensure_node() {
    if jail_exec command -v node >/dev/null 2>&1; then
        log "Node.js already present: $(jail_exec node --version)"
        return 0
    fi

    log "Installing Node.js ($NODE_PKG) and npm ($NPM_PKG) ..."
    jail_exec pkg install -y "$NODE_PKG" "$NPM_PKG"

    if ! jail_exec command -v node >/dev/null 2>&1; then
        die "Failed to install Node.js in jail '$TENANT'."
    fi

    log "Node.js installed: $(jail_exec node --version)"
}

# ---------------------------------------------------------------------------
# Tool installation
# ---------------------------------------------------------------------------

install_tool() {
    tool="$1"

    case "$tool" in
        claude)
            npm_pkg="$CLAUDE_PKG"
            bin_name="claude"
            ;;
        codex)
            npm_pkg="$CODEX_PKG"
            bin_name="codex"
            ;;
        gemini)
            npm_pkg="$GEMINI_PKG"
            bin_name="gemini"
            ;;
        *)
            log "WARNING: Unknown tool '$tool' — skipping."
            return 0
            ;;
    esac

    # Check if already installed
    if jail_exec command -v "$bin_name" >/dev/null 2>&1; then
        log "Tool '$tool' is already installed."
        return 0
    fi

    log "Installing $tool ($npm_pkg) ..."
    jail_exec npm install -g "$npm_pkg"

    if jail_exec command -v "$bin_name" >/dev/null 2>&1; then
        version=$(jail_exec "$bin_name" --version 2>/dev/null || echo "installed")
        log "Installed $tool: $version"
    else
        log "WARNING: $tool installed but binary '$bin_name' not found in PATH."
    fi
}

# ---------------------------------------------------------------------------
# PF rules for AI API access
# ---------------------------------------------------------------------------

configure_pf_rules() {
    tools="$1"
    tenant_ip="$2"

    pf_anchor_file="/etc/pf.anchors/${PF_ANCHOR}-${TENANT}"
    allowed_hosts=""

    # Build list of allowed API hosts based on provisioned tools
    OLD_IFS="$IFS"
    IFS=','
    for tool in $tools; do
        case "$tool" in
            claude)  allowed_hosts="$allowed_hosts $CLAUDE_HOSTS" ;;
            codex)   allowed_hosts="$allowed_hosts $CODEX_HOSTS" ;;
            gemini)  allowed_hosts="$allowed_hosts $GEMINI_HOSTS" ;;
        esac
    done
    IFS="$OLD_IFS"

    if [ -z "$allowed_hosts" ]; then
        return 0
    fi

    log "Configuring PF rules for tenant '$TENANT' AI API access ..."

    # Write anchor rules
    {
        printf '# SparrowOS AI API access rules for tenant: %s\n' "$TENANT"
        printf '# Auto-generated by tenant-ai-provision.sh\n\n'
        for host in $allowed_hosts; do
            printf 'pass out quick on egress proto tcp from %s to <%s> port { 443 }\n' \
                "$tenant_ip" "$host"
        done
    } > "$pf_anchor_file"

    # Ensure anchor is referenced in pf.conf
    anchor_name="${PF_ANCHOR}-${TENANT}"
    if ! grep -q "anchor \"${anchor_name}\"" /etc/pf.conf 2>/dev/null; then
        printf '\nanchor "%s"\nload anchor "%s" from "%s"\n' \
            "$anchor_name" "$anchor_name" "$pf_anchor_file" >> /etc/pf.conf
    fi

    # Reload PF
    pfctl -f /etc/pf.conf 2>/dev/null || true
    log "PF rules applied for $allowed_hosts"
}

# ---------------------------------------------------------------------------
# Update tenant config
# ---------------------------------------------------------------------------

update_tenant_conf() {
    tools="$1"
    conf="${SPARROW_CONF_DIR}/${TENANT}/tenant.conf"

    if [ ! -f "$conf" ]; then
        log "WARNING: Tenant config not found at $conf — skipping update."
        return 0
    fi

    # Update the TENANT_AI_TOOLS line
    if grep -q '^TENANT_AI_TOOLS=' "$conf"; then
        # Merge existing tools with newly provisioned ones
        existing=$(grep '^TENANT_AI_TOOLS=' "$conf" | cut -d'"' -f2)
        merged=$(printf '%s,%s' "$existing" "$tools" | tr ',' '\n' | sort -u | tr '\n' ',' | sed 's/,$//')
        sed -i '' "s|^TENANT_AI_TOOLS=.*|TENANT_AI_TOOLS=\"${merged}\"|" "$conf" 2>/dev/null || \
        sed -i "s|^TENANT_AI_TOOLS=.*|TENANT_AI_TOOLS=\"${merged}\"|" "$conf"
    else
        printf 'TENANT_AI_TOOLS="%s"\n' "$tools" >> "$conf"
    fi

    log "Updated tenant config: TENANT_AI_TOOLS"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    if [ $# -lt 2 ]; then
        usage
    fi

    TENANT="$1"
    TOOLS="$2"

    if [ "$(id -u)" -ne 0 ]; then
        die "This script must be run as root."
    fi

    # Verify jail is running
    if ! jls -j "$TENANT" >/dev/null 2>&1; then
        die "Jail '$TENANT' is not running."
    fi

    # Load tenant config for IP address
    conf="${SPARROW_CONF_DIR}/${TENANT}/tenant.conf"
    if [ -f "$conf" ]; then
        # shellcheck disable=SC1090
        . "$conf"
    fi
    tenant_ip="${TENANT_IP:-}"

    log "Provisioning AI tools for tenant '$TENANT': $TOOLS"

    # Ensure Node.js is available
    ensure_node

    # Install each requested tool
    OLD_IFS="$IFS"
    IFS=','
    for tool in $TOOLS; do
        install_tool "$tool"
    done
    IFS="$OLD_IFS"

    # Configure PF rules for API access
    if [ -n "$tenant_ip" ]; then
        configure_pf_rules "$TOOLS" "$tenant_ip"
    else
        log "WARNING: TENANT_IP not set — skipping PF rule configuration."
    fi

    # Update tenant config
    update_tenant_conf "$TOOLS"

    log "AI tool provisioning complete for '$TENANT'."
}

main "$@"
