#!/bin/sh
# SparrowOS — VNET bridge networking setup for tenant jails
#
# Creates a shared bridge interface (bridge0) that tenant epair interfaces
# attach to.  Enables IP forwarding and configures PF NAT so that tenant
# traffic can reach the outside network.
#
# Usage:  bridge-setup.sh [ext_iface]
#   ext_iface — external (uplink) interface name (default: auto-detect)
#
# Must be run as root.

set -eu

BRIDGE="bridge0"
TENANT_SUBNET="10.99.0.0/16"
PF_ANCHOR="sparrow-tenant-nat"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log() {
    printf '[sparrow-bridge] %s\n' "$*"
}

die() {
    log "ERROR: $*" >&2
    exit 1
}

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        die "This script must be run as root."
    fi
}

detect_ext_iface() {
    # Pick the interface that holds the default route
    route -n get default 2>/dev/null | awk '/interface:/{print $2}'
}

# ---------------------------------------------------------------------------
# Bridge creation
# ---------------------------------------------------------------------------

create_bridge() {
    if ifconfig "$BRIDGE" >/dev/null 2>&1; then
        log "Bridge $BRIDGE already exists — skipping creation."
    else
        log "Creating bridge $BRIDGE ..."
        ifconfig "$BRIDGE" create
        ifconfig "$BRIDGE" up
        log "Bridge $BRIDGE is up."
    fi

    # Assign the gateway address for the tenant subnet
    if ! ifconfig "$BRIDGE" | grep -q "inet 10.99.0.1"; then
        ifconfig "$BRIDGE" inet 10.99.0.1/16
        log "Assigned 10.99.0.1/16 to $BRIDGE."
    fi
}

# ---------------------------------------------------------------------------
# IP forwarding
# ---------------------------------------------------------------------------

enable_forwarding() {
    cur=$(sysctl -n net.inet.ip.forwarding)
    if [ "$cur" -eq 1 ]; then
        log "IP forwarding is already enabled."
    else
        sysctl net.inet.ip.forwarding=1
        log "IP forwarding enabled."
    fi
}

# ---------------------------------------------------------------------------
# PF NAT configuration
# ---------------------------------------------------------------------------

configure_nat() {
    ext_iface="$1"

    log "Configuring PF NAT on $ext_iface for $TENANT_SUBNET ..."

    # Write an anchor rule file
    pf_anchor_file="/etc/pf.anchors/${PF_ANCHOR}"

    cat > "$pf_anchor_file" <<EOF
# SparrowOS tenant NAT — auto-generated by bridge-setup.sh
nat on ${ext_iface} from ${TENANT_SUBNET} to any -> (${ext_iface})
pass in  on ${BRIDGE} from ${TENANT_SUBNET} to any keep state
pass out on ${ext_iface} from ${TENANT_SUBNET} to any keep state
EOF

    # Ensure the anchor is loaded in pf.conf if not already present
    if ! grep -q "anchor \"${PF_ANCHOR}\"" /etc/pf.conf 2>/dev/null; then
        log "Adding anchor reference to /etc/pf.conf ..."
        printf '\nanchor "%s"\nload anchor "%s" from "%s"\n' \
            "$PF_ANCHOR" "$PF_ANCHOR" "$pf_anchor_file" >> /etc/pf.conf
    fi

    # Reload PF
    pfctl -f /etc/pf.conf 2>/dev/null || true
    pfctl -e 2>/dev/null || true
    log "PF NAT configuration applied."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    require_root

    ext_iface="${1:-}"
    if [ -z "$ext_iface" ]; then
        ext_iface=$(detect_ext_iface)
        [ -n "$ext_iface" ] || die "Could not auto-detect external interface."
        log "Auto-detected external interface: $ext_iface"
    fi

    create_bridge
    enable_forwarding
    configure_nat "$ext_iface"

    log "Bridge networking setup complete."
}

main "$@"
